runtime: python37


instance_class: F2

# env: flex
# manual_scaling:
#   instances: 1

# resources:
#   cpu: 1
#   memory_gb: 0.5
#   disk_size_gb: 10

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto